import { sendOTPVerificationEmail } from "../../lib/mailer";
import { getRefreshToken } from "./authorize-user";
import { trustDevice } from "./device-trust";
import { getUserById } from "../user/users";
import { randomUUID } from "node:crypto";
import { prisma } from "../../lib/db";
import { isFuture } from "date-fns";
import bcrypt from 'bcrypt';

/**
 * @verifyOTP function validates user credentails and returns a signed JWT
 * @param userId string, unique uuid() generated by db at sign-up
 * @param otp string, a 6 digit otp sent to user email
 * 
 * @returns
 * ```
 * Promise<{
 *     status: number,
 *     message: string,
 *     data?: {
 *         userId: string,
 *         firstName: string,
 *         lastName: string,
 *         username: string | undefined,
 *         email: string,
 *         auth_time: Date
 *     }
 * }>
 * ```
 * 
 * - userId is used to fetch otp_hash from db
 * - otp_hash is checked for expiration, if expired it is deleted
 * - Then OTP is compared with otp_hash, if success it gets deleted
 * - If match fails, an error status and message is returned
 */

type VerifyOTPReturnType = {
    status: number,
    message: string,
    payload?: {
        userId: string,
        firstName: string,
        lastName?: string,
        email: string,
        auth_time: Date,
    },
    refreshToken?: string
    newDeviceId?: string
}

export async function verifyOTP(
    data: {
        userId: string,
        jti: string,
    },
    otp: string,
    ipAddress: string | null,
    userAgent: string | null,
    deviceId: string | null
): Promise<VerifyOTPReturnType> {
    try {
        const UserOTPRecord = await prisma.userOTPVerification.findFirst({
            where: { userId: data.userId, id: data.jti },
            orderBy: { createdAt: 'desc' },
            select: {
                expiresAt: true,
                otp: true,
            }
        });

        if (!UserOTPRecord) return { status: 400, message: "OTP Record not found" }
        if (!isFuture(UserOTPRecord?.expiresAt)) {
            await prisma.userOTPVerification.deleteMany({ where: { userId: data.userId } })
            return { status: 400, message: "OTP has expired" }
        }

        const verified = await bcrypt.compare(otp, UserOTPRecord.otp)
        if (!verified) return { status: 400, message: "Incorrect OTP, Account not verified!" }

        const user = await prisma.user.update({
            where: { id: data.userId },
            data: { verified: true },
        });
        await prisma.userOTPVerification.deleteMany({ where: { userId: data.userId } })

        const session = await prisma.session.create({
            data: { userId: data.userId, ipAddress, userAgent },
            select: { id: true, createdAt: true }
        });
        const { refreshToken, success, ...tokenRes } = await getRefreshToken(session.id);
        if (!success || !refreshToken) return tokenRes;

        let newDeviceId: string | undefined;
        if (!deviceId) newDeviceId = randomUUID();

        if (newDeviceId) await trustDevice(data.userId, newDeviceId, ipAddress, userAgent)

        return {
            status: 200,
            message: "User account has been verified!",
            payload: {
                userId: user.id,
                firstName: user?.firstName,
                lastName: user?.lastName ?? undefined,
                email: user.email,
                auth_time: session.createdAt,
            },
            refreshToken,
            newDeviceId,
        }
    } catch (error) {
        return { status: 500, message: "Internal Server Error!" }
    }
}

/**
 * @resendOTPVerificationEmail function validates user credentails and returns a signed JWT
 * @param userId string, unique uuid() generated by db at sign-up
 * 
 * @returns
 * ```
 * Promise<{
 *     status: number,
 *     message: string,
 * }>
 * ```
 * 
 * - First, an account check is made using userId
 * - Then, the function calls @sendOTPVerificationEmail function
 */

type resendOTPReturnType = {
    success: boolean,
    status: number,
    message: string,
    details?: string,
    data?: {
        userId: string,
        email: string,
        purpose: string,
        jti: string
    }
}

export async function resendOTPVerificationEmail(userId: string, jti: string): Promise<resendOTPReturnType> {
    try {
        await prisma.userOTPVerification.deleteMany({ where: { userId: userId, id: jti } })

        const user = await getUserById(userId);
        if (!user) return { success: false, status: 404, message: "User account does not exist!" }

        const { success, data, ...otpRes } = await sendOTPVerificationEmail(user.id, user.email)
        if (!success || !data) return { success, ...otpRes }

        return {
            status: 200,
            success: true,
            message: "OTP sent! Check you email.",
            data: {
                userId: data.userId,
                email: data.email,
                purpose: 'email_verification',
                jti: data.otpId,
            }
        }
    } catch (error) {
        return { success: false, status: 500, message: "Coudn't Resend OTP!", details: error instanceof Error ? error.message : "Internal Server Error!" }
    }
}