import { sendOTPVerificationEmail } from "../../lib/mailer";
import { getUserById } from "../user/users";
import { prisma } from "../../lib/db";
import { isFuture } from "date-fns";
import bcrypt from 'bcrypt';

/**
 * @verifyOTP function validates user credentails and returns a signed JWT
 * @param userId string, unique uuid() generated by db at sign-up
 * @param otp string, a 6 digit otp sent to user email
 * 
 * @returns
 * ```
 * Promise<{
 *     status: number,
 *     message: string,
 *     data?: {
 *         userId: string,
 *         firstName: string,
 *         lastName: string,
 *         username: string | undefined,
 *         email: string,
 *         auth_time: Date
 *     }
 * }>
 * ```
 * 
 * - userId is used to fetch otp_hash from db
 * - otp_hash is checked for expiration, if expired it is deleted
 * - Then OTP is compared with otp_hash, if success it gets deleted
 * - If match fails, an error status and message is returned
 */

export async function verifyOTP(userId: string, otp: string) {
    try {
        const UserOTPRecord = await prisma.userOTPVerification.findFirst({
            where: { userId },
            orderBy: { createdAt: 'desc' },
            select: {
                expiresAt: true,
                otp: true,
            }
        });

        if (!UserOTPRecord) return { status: 400, message: "OTP Record not found" }
        if (!isFuture(UserOTPRecord?.expiresAt)) {
            await prisma.userOTPVerification.deleteMany({ where: { userId } })
            return { status: 400, message: "OTP has expired" }
        }

        const verified = await bcrypt.compare(otp, UserOTPRecord.otp)
        if (!verified) return { status: 400, message: "Incorrect OTP, Account not verified!" }

        const user = await prisma.user.update({
            where: { id: userId },
            data: { verified: true },
        });
        await prisma.userOTPVerification.deleteMany({ where: { userId } })

        return {
            status: 200,
            message: "User account has been verified!",
            data: {
                userId: user.id,
                firstName: user?.firstName,
                lastName: user?.lastName ?? undefined,
                username: user.username,
                email: user.email,
                auth_time: new Date(),
            }
        }
    } catch (error) {
        console.error(error)
        return { status: 500, message: "Internal Server Error!" }
    }
}

/**
 * @resendOTPVerificationEmail function validates user credentails and returns a signed JWT
 * @param userId string, unique uuid() generated by db at sign-up
 * 
 * @returns
 * ```
 * Promise<{
 *     status: number,
 *     message: string,
 * }>
 * ```
 * 
 * - First, an account check is made using userId
 * - Then, the function calls @sendOTPVerificationEmail function
 */

export async function resendOTPVerificationEmail(userId: string) {
    try {
        await prisma.userOTPVerification.deleteMany({ where: { userId } })

        const user = await getUserById(userId);
        if (!user) return { status: 404, message: "User account does not exist!" }

        return await sendOTPVerificationEmail(user.id, user.email)
    } catch (error) {
        console.error(error)
        return { status: 500, message: "Internal Server Error!" }
    }
}