import 'dotenv';
import nodemailer from 'nodemailer';
import { add } from 'date-fns';
import { prisma } from './db';
import bcrypt from 'bcrypt';

/**
 * @transporter nodemailer configuration with OAuth2 for sending email to users using gmail
 * #### Important Variables
 * `AUTH_EMAIL:`            It is used as the sender email for sending those damn emails, as configured in app
 * `GOOGLE_CLIENT_ID:`      It is the google client id of your app at google cloud console
 * `GOOGLE_CLIENT_SECRET:`  It is your google client secret, make sure it remains a secret
 * `GOOGLE_REFRESH_TOKEN:`  It is the refresh token for your app, use a permanent refresh token
 */

const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
        type: 'OAuth2',
        user: process.env.AUTH_EMAIL,
        clientId: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET,
        refreshToken: process.env.GOOGLE_REFRESH_TOKEN,
    }
})

// verifying connection with google app
transporter.verify((error, success) => {
    if (error) console.error(error)
    else console.log(`Ready for messages.\n${success}`)
})

/**
 * @sendOTPVerificationEmail 
 * @param userId string, unique uuid() generated by db at sign-up
 * @param email string, user email
 * 
 * @returns 
 * ```
 * Promise<{
 *      status: number,
 *      message: string,
 *      data: {
 *          userId: string,
 *          email: string,
 *      }
 * }>
 * ```
 * 
 * An OTP is generated, hashed, stored in database,
 * and sent to the user email
 * with an html template for acconunt verification
 * 
 * The OTP is set to expire within an hour.
 */

export async function sendOTPVerificationEmail(userId: string, email: string) {
    try {
        const otp = `${Math.floor(100000 + Math.random() * 900000)}`;
        const mailOptions = {
            from: process.env.AUTH_EMAIL,
            to: email,
            subject: "[HQ] Network Access Clearance",
            html: `<div style="font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #0a0a0a; padding: 40px 20px; color: #e0e0e0;">
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 520px; background-color: #141414; border-radius: 8px; overflow: hidden; border: 1px solid #2a2a2a;">
                    <tr>
                        <td style="padding: 40px 20px 20px; text-align: center; border-bottom: 1px solid #2a2a2a;">
                            <span style="font-size: 20px; font-weight: 700; letter-spacing: 6px; color: #ffffff;">HEADQUARTERS</span><br>
                            <span style="font-size: 10px; font-weight: 500; letter-spacing: 2px; color: #666666; text-transform: uppercase;">Internal Systems</span>
                        </td>
                    </tr>
                
                    <tr>
                        <td style="padding: 40px;">
                            <h2 style="margin-top: 0; color: #ffffff; font-size: 18px; font-weight: 500; letter-spacing: 1px;">Access Clearance Required</h2>
                            <p style="font-size: 14px; line-height: 1.6; color: #a0a0a0;">
                                A request to access the central hub has been initiated. To proceed with authentication, please use the clearance code provided below. This authorization token will expire in 10 minutes.
                            </p>
                
                            <div style="margin: 35px 0; padding: 20px; background-color: #050505; border-radius: 4px; border: 1px solid #333333; text-align: center;">
                                <span style="font-family: 'JetBrains Mono', 'Courier New', Courier, monospace; font-size: 32px; font-weight: bold; letter-spacing: 12px; color: #e53935;">
                                    ${otp}
                                </span>
                            </div>
                
                            <p style="font-size: 12px; color: #666666; line-height: 1.5;">
                                If you did not initiate this access request, no further action is required. The network remains secure.
                            </p>
                        </td>
                    </tr>
                
                    <tr>
                        <td style="padding: 25px; text-align: center; font-size: 11px; color: #444444; background-color: #0f0f0f; border-top: 1px solid #2a2a2a;">
                            Automated Dispatch <br>
                            <strong>HQ Central Hub</strong>
                        </td>
                    </tr>
                </table>
            </div>`
        };

        const otp_hash = await bcrypt.hash(otp, 10)
        const expiresAt = add(Date.now(), { minutes: 10 })

        const otpData = await prisma.userOTPVerification.create({
            data: {
                userId,
                otp: otp_hash,
                expiresAt,
            },
        });

        await transporter.sendMail(mailOptions);

        return {
            success: true,
            status: 200,
            message: 'Verification email sent',
            data: { userId: otpData.userId, email, otpId: otpData.id }
        };
    } catch (error) {
        console.error(error);
        return {
            success: false,
            status: 500,
            message: "Coudln't Send Verification Email!",
            details: error instanceof Error ? error.message : "Internal Server Error!"
        };
    }
}