import 'dotenv';
import nodemailer from 'nodemailer';
import { add } from 'date-fns';
import { prisma } from './db';
import bcrypt from 'bcrypt';

/**
 * @transporter nodemailer configuration with OAuth2 for sending email to users using gmail
 * #### Important Variables
 * `AUTH_EMAIL:`            It is used as the sender email for sending those damn emails, as configured in app
 * `GOOGLE_CLIENT_ID:`      It is the google client id of your app at google cloud console
 * `GOOGLE_CLIENT_SECRET:`  It is your google client secret, make sure it remains a secret
 * `GOOGLE_REFRESH_TOKEN:`  It is the refresh token for your app, use a permanent refresh token
 */

const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
        type: 'OAuth2',
        user: process.env.AUTH_EMAIL,
        clientId: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET,
        refreshToken: process.env.GOOGLE_REFRESH_TOKEN,
    }
})

// verifying connection with google app
transporter.verify((error, success) => {
    if (error) console.error(error)
    else console.log(`Ready for messages.\n${success}`)
})

/**
 * @sendOTPVerificationEmail 
 * @param userId string, unique uuid() generated by db at sign-up
 * @param email string, user email
 * 
 * @returns 
 * ```
 * Promise<{
 *      status: number,
 *      message: string,
 *      data: {
 *          userId: string,
 *          email: string,
 *      }
 * }>
 * ```
 * 
 * An OTP is generated, hashed, stored in database,
 * and sent to the user email
 * with an html template for acconunt verification
 * 
 * The OTP is set to expire within an hour.
 */

export async function sendOTPVerificationEmail(userId: string, email: string) {
    try {
        const otp = `${Math.floor(100000 + Math.random() * 900000)}`;
        console.log(otp) // TODO: JUST FOR DEVELOPEMNT
        const mailOptions = {
            from: process.env.AUTH_EMAIL,
            to: email,
            subject: "Account Verification – Vendly",
            html: `<div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f9f9f9; padding: 20px; color: #333;">
                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 500px; background-color: #ffffff; border-radius: 12px; overflow: hidden; border: 1px solid #eeeeee;">
                    <tr>
                        <td style="padding: 30px 20px; text-align: center; background-color: #ffffff;">
                            <span style="font-size: 24px; font-weight: 900; letter-spacing: 4px; color: #000000;">VENDLY</span>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding: 20px 40px; text-align: center;">
                            <h2 style="margin-top: 0; color: #111; font-size: 20px;">Verify your email</h2>
                            <p style="font-size: 15px; line-height: 1.5; color: #666;">
                                Enter the following code to finish setting up your Vendly account. This code will expire in 1 hour.
                            </p>

                            <div style="margin: 30px 0; padding: 15px; background-color: #f3f3f3; border-radius: 8px; border: 1px dashed #cccccc;">
                                <span style="font-family: 'Courier New', Courier, monospace; font-size: 36px; font-weight: bold; letter-spacing: 8px; color: #007bff;">
                                    ${otp}
                                </span>
                            </div>

                            <p style="font-size: 13px; color: #999;">
                                If you didn't request this code, you can safely ignore this email.
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding: 30px; text-align: center; font-size: 12px; color: #bbbbbb; border-top: 1px solid #f0f0f0;">
                            Sent by Vendly Marketplace <br>
                            vendly.pk
                        </td>
                    </tr>
                </table>
            </div>`
        };

        const otp_hash = await bcrypt.hash(otp, 10)
        const expiresAt = add(Date.now(), { hours: 1 })

        await prisma.userOTPVerification.create({
            data: {
                userId,
                otp: otp_hash,
                expiresAt,
            },
        });

        await transporter.sendMail(mailOptions);

        return { status: 200, message: 'Verification email sent', data: { userId, email } };
    } catch (error) {
        console.error(error);
        return { status: 500, message: 'Internal Server Error!' };
    }
}